@startuml
'Validator
abstract class IValidatorChain {
	#nextValidator: IValidatorChain
	#regexPat: Regex
	{abstract} +isValid(line:str): bool
	+setNextValidator(chain: IValidatorChain)
}
'Ex: "Narrator" "Player listen to me..."
class CharacterStrategy
class BasicCharacterStrategy

class ObjectStrategy {
	-definedSpeakers: List<str>
	'Map[file_url][hasChanged or lines in file]
	+setDefinedSpeakers(fileMap: Map<str,Map<str,bool|List<str>>>)
}
'Ex: narr "Player, please select this choice."
class BasicObjectStrategy
class CustomObjectStrategy

class ItalicStrategy
class ParenthesisStrategy
'Ex: "{i}What am I thinking! I can't do that... right?{/i}" OR
'Ex: "Player" "{i}What am I thinking! I can't do that... right?{/i}"
class CustomTextTagStrategy
'Ex: "Marco jumps over the fence, scrapping his arm in the process"
class BasicStrategy

'File Descriptors
class Reader {
	+readLines(fileURL: str): Dictionary<str,List<str>>
	+walkFiles(rootDir:str): List<str>
}
class RenpyReader {
  +walkFiles(rootDir:str): List<str>
}
class Writer {
	+writeLines(fileURL: str,lines: List<str>)
}
class Deleter {
	+delete(fileURL: str)
}

'ThreadExecutors
class  FileExecutor <<Singleton>>{
	{static}+fileLines(reader:Reader,rootDir:str): List<Dictionary<str,List<str>>>
	{static}+writeFiles(writer:Writer,fileInfo:Dictionary<str,List<str>>)
}

'Narrator
class  NarratorHandler <<Singleton>>{
	+remove(IValidatorChain,lines:Map<str,Map<str,bool|List<str>>>)
	-cleanup(lines: Map<str,Map<str,bool|List<str>>>)
	-correctIndentation(lines: Map<str,Map<str,bool|List<str>>>)
	-cleanPause(lines: Map<str,Map<str,bool|List<str>>>)
}
class  ErrorFixer <<Singleton>>{
	-destPat: Regex
	-typePat: Regex
	-lineNumPat: Regex
	-getErrors(reader:FileReader): Map<str,List<Map<str,str|int>>>
	-correctErrors(errors: Map<str,List<Map<str,str|int>>>,reader: FileReader,writer: FileWriter, deleter: FileDeleter)
}

'Argument Classes
class CLIParser {
    -parser: ArgumentParser
    -setup()
    -initParser()
    -configureOpts()
    +getArgs(commands:str)
}
class ArgChecker {
    -parser: CLIParser
    -validate()
    +getArgs(): Namespace
}

'Validator Relations
IValidatorChain <|-- BasicStrategy
IValidatorChain <|-- CustomTextTagStrategy
IValidatorChain <|-- ParenthesisStrategy
IValidatorChain <|-- ItalicStrategy
IValidatorChain <|-- ObjectStrategy
IValidatorChain <|-- CharacterStrategy
CharacterStrategy <|-- BasicCharacterStrategy
ObjectStrategy <|-- CustomObjectStrategy
ObjectStrategy <|-- BasicObjectStrategy
Reader <|-- RenpyReader

'Argument Relations
ArgChecker --> CLIParser : uses
@enduml
