@startuml
hide empty members
'Validators
abstract class IValidatorChain {
	#nextValidator: IValidatorChain
	{abstract} +isValid(line:str): bool
	+setNextValidator(chain: IValidatorChain)
}
abstract class IValidatorChainSolo {
	#validatePat: Regex
  +isValid(line:str): bool
}
class ObjectStrategy {
	{static}#speakerObjects: Set<str>
  {static}-objNamePat: Regex
  {static}#charItemPats: List<Regex>
  {static}#validatePat: Regex
  {static}-initCharItems(charItems: List<Rule>)
  {static}+reset()
  +defineSpeakers(fileInfos: List<FileInfo>)
  +isValid(line:str): bool
}
class NullStrategy

'Validator Rules
dataclass Rule {
    +pattern: Regex
}
dataclass CharRule
dataclass BasicCharRule
dataclass CueRule
dataclass TextTagRule
dataclass ObjectRule
dataclass BasicObjectRule
dataclass VarObjectRule
dataclass QuoteCueRule
dataclass QuoteTextTagRule



'File Descriptors
class Reader {
  +readLines(fileURL: Union[str,Path]): FileInfo
  +walkFiles(rootDir:str): List<str>
}
class Writer {
  +writeLines(fileInfo:FileInfo)
  {static}+backupDir(filePaths:List<str>,backupDirPath:Path)
  {static}+printStats(total_lines:int, total_cleaned:int)
}
class Deleter {
	+delete(fileURL: str)
}

'File Filters
abstract class BaseFilter {
   #folderFilterSet: Set<str>
   #fileFilterSet: Set<str>
   {abstract}+isInvalidFolder(dirPath: str): bool
   {abstract}+isValidFile(fileName:str): bool
}
abstract class RenpyFilter {
  {static}#fileExt: str
  #globFilterSet: Set<str>
  {abstract}#hasPassedFileGlob(fileName:str): bool
  {abstract}#hasPassedFileLiteral(fileName:str): bool
  +isValidFile(fileName:str): bool
}
class InvalidRenpyFilter {
  #hasPassedFileGlob(fileName:str): bool
  #hasPassedFileLiteral(fileName:str): bool
  +isInvalidFolder(dirPath: str):bool
}
class ValidRenpyFilter {
   #hasPassedFileGlob(fileName:str): bool
   #hasPassedFileLiteral(fileName:str): bool
   +isInvalidFolder(dirPath: str):bool
}

'ThreadExecutors
class  FileExecutor <<Singleton>>{
	{static}+fileLines(reader:Reader,arg:Namespace): List<FileInfo>
  {static}+writeFiles(writer:Writer,fileInfos:List<FileInfo>)
  {static}+fix_errors(error_txt:Path,reader:Reader)
  {static}-fixFunc(errors: List<RenpyError>)
}

'Handler Info
class AtlInfo {
  +isAtl: bool
  +indentNum: int
  -altPat: Regex
  {static}+isBlock(stripLine:str): bool
}
class LineInfo {
  {static}-SINGLE_QUOTE:str
  {static}-DOUBLE_QUOTE: str
  {static}-SINGLE_TRIPLE_QUOTE: str
  {static}-DOUBLE_TRIPLE_QUOTE: str
  {static}-HASH: str
  #stripLine: str
  #isComment: bool
  #isTripleQuote: bool
  #isTripleQuoteEnd: bool
  #hasTripleQuote: bool
  #isMenu: bool
  +hasLooseDoubleQuote(): bool
  +setup(line:str)
  {static}-isAComment(stripLine:str): bool
  {static}-startswitchTripleQuote(stripLine:str): bool
  {static}-hasTripleQuote(stripLine:str): bool
  {static}-endswithTripleQuote(stripLine:str): bool
  {static}-isChoiceMenu(stripLine:str): bool
}
class MultiLineInfo {
  +multiType: MultiLineType
  +isChoiceMenu: bool
  #lines: List<str>
  +clear()
  +append(line:str)
  +isEmpty(): bool
  +reset()
}
class PrevInfo {
  +line: str
  +reset()
}
class PrevMultiInfo {
  #multiInfo: MultiLineInfo
  +isNarr: bool
  +appendLine(line:str)
  +clearList()
  +isEmptyList(): bool
  +getLines(): List<str>
  +reset()
}
class PrevIndentInfo {
  #indentNum: int
  #hasReset: bool
  +reset()
}
class PauseInfo {
  -isPause: bool
  -isPrevPause: bool
  +setPause(value:bool)
  +isDuplicate(): bool
  +snapshotPauseState()
}

'Narrator Handler
class  NarratorHandler <<Singleton>>{
  {static}+PAUSE_STATEMENTS:tuple<str>
  {static}-closingPat: Regex
  {static}-totalLines: int
  {static}-totalCleanedLines: int
  {static}+remove(fileInfos:List<FileInfo>,args:Namespace): List<Dictionary<str,List<str>>>
  {static}+getIdentNum(line:str):int
  {static}-isClosing(line:str):bool
  {static}-resetLineStats()
  {static}+lineStats(): Tuple<int,int>
  {static}-correctIndent(fileInfos:List<FileInfo>): List<FileInfo>
  {static}-pauseFilter(fileInfos:List<FileInfo>): List<FileInfo>
}
class  ErrorFixer {
  {static}-destPat: Regex
  {static}-typePat: Regex
  {static}-lineNumPat: Regex
  {static}-projectDir:Union[str,None]
  +fix(errors: List<RenpyError>,reader:Reader,writer:Writer,deleter:Deleter)
  {static}+getErrors(errors_txt:Path, reader:Reader): Dictionary<str,List<RenpyError>>
  {static}-addError(errors: Dictionary<str,List<RenpyError>>,error: RenpyError)
  {static}-getError(line:str): RenpyError
  {static}-dedentLines(lines:List<str>,startIndex: int,startIndent: Union[int,None]): List<str>
  {static}-reverseDedentLines(lines:List<str>,startIndex: int): List<str>
}
dataclass FileInfo {
  +url:str
  +lines: List<str>
}
dataclass RenpyError {
  +line_num:Union[int,None]
  +file_loc:Union[str,None]
  +category:Union[str,None]
}

'Argument Classes
class CLIParser {
    -parser: ArgumentParser
    -setup()
    -initParser()
    -configureOpts()
    +getArgs(commands:str)
}
class ArgChecker {
    {static}+checkArgs(args: Namespace)
    {static}-validateFolderOrFileArg(folderOrFileArg: Path)
}
class ArgAssembler {
  {static}-nargValidators: Dictionary<str,Type<IValidatorChain>>
  {static}-quoteValidators: List<IValidatorChain>
  {static}+assemble(args:Namespace)
  {static}-convertFilters(args:Namespace)
  {static}-getFilters(optionName:str): Union<IValidatorChain, List<IValidatorChain>>
  {static}-escape(args:Namespace, arg_filter_val: Union<List<str>,None>>): Union<str,List<str>,None>
  {static}-nargFilter(validator:Union<IValidatorChain,None>,arg_filter: Union<str,List<str>,None>,filterName:str, ruleType: Type<Rule>): IValidatorChain
  {static}-quoteFilter(args:Namespace)
  {static}-quoteNArgs(validator:Union<IValidatorChain,None>, argFilter: Union<str,List<str>,None>,filterType: Type<IValidatorChain>, ruleType: Type<Rule>)
}

'Enums
enum DialogueRules {
  BASIC
  ITALIC
  ONLY_PUNCTUATION
  PARENTHESIS
  TILDA_EXPRESSION_CUE
  ASTERISK_EXPRESSION_CUE
  TEXT_TAG
  GUILLEMET_SINGLE
  GUILLEMET_DOUBLE
}

enum SpeakerRules {
  CHARACTER
  CHARACTER_BASIC
  CHARACTER_NONE
  OBJECT
  OBJECT_ITALIC
  OBJECT_NONE
  OBJECT_VAR
}

enum QuoteRules {
  EXPRESSION_CUE_TILDA
  EXPRESSION_CUE_ASTERISK
  ITALIC
  ONLY_PUNCTUATION
  PARENTHESIS
  TEXT_TAG
  GUILLEMET_SINGLE
  GUILLEMET_DOUBLE
}

enum FilterTag {
  BASIC_CHAR
  NONE_CHAR
  ITALIC_NARR
  PARENTHESIS_NARR
  BASIC_NARR
  BASIC_CHAR_OBJ
  NONE_CHAR_OBJ
  EXPRESSION_CUES
  ONLY_PUNCTUATIONS
  GUILLEMETS
  NO_CUSTOM_CHAR_OBJS
  NO_CUSTOM_TEXT_TAGS
  NO_CUSTOM_CHARS
}

enum MultiLineType {
  NONE
  SINGLE_QUOTE
  TRIPLE_QUOTE 
  VALID_TRIPLE_QUOTE
  VALID_SINGLE_QUOTE
}

'File Filters Relations
BaseFilter <|-- RenpyFilter
RenpyFilter <|-- InvalidRenpyFilter
RenpyFilter <|-- ValidRenpyFilter

'Info Relations
PrevInfo <|-- PrevIndentInfo
PrevInfo <|-- PrevMultiInfo
MultiLineInfo o-- PrevMultiInfo

'Handler Relations
NarratorHandler --> PrevIndentInfo : uses
NarratorHandler --> PrevMultiInfo : uses
NarratorHandler --> AltInfo : uses
NarratorHandler --> LineInfo : uses
NarratorHandler --> PauseInfo : uses

'Validator Relations
IValidatorChain <|-- ObjectStrategy
IValidatorChain <|-- IValidatorChainSolo
IValidatorChainSolo <|-- NullStrategy
IValidatorChainSolo ..> Rule : uses

'Rules Relations
Rule <|-- CharRule
Rule <|-- CueRule
Rule <|-- TextTagRule
Rule <|-- ObjectRule
Rule <|-- VarObjectRule
Rule <|-- TQCueRule
Rule <|-- TQTextTagRule
CharRule <|-- BasicCharRule
ObjectRule <|-- BasicObjectRule


'Argument Relations
ArgChecker ..> CLIParser : uses
ArgAssembler ..> CLIParser : uses
@enduml
