@startuml
hide empty members
'Validator
abstract class IValidatorChain {
	#nextValidator: IValidatorChain
	{abstract} +isValid(line:str): bool
	+setNextValidator(chain: IValidatorChain)
}
abstract class IValidatorChainSolo {
	#validatePat: Regex
  +isValid(line:str): bool
}
'Ex: "Narrator" "Player listen to me..."
class CharacterStrategy
class BasicCharacterStrategy

class ObjectStrategy {
	{static}#speakerObjects: Set<str>
  {static}-objNamePat: Regex
  {static}#charItemPats: List<Regex>
  {static}#validatePat: Regex
  {static}-initCharItem(char_item: str|list<str>|None)
  {static}+reset()
	+defineSpeakers(fileInfos: List<FileInfo>)
  +isValid(line:str): bool
}
'Ex: narr "Player, please select this choice."
class BasicObjectStrategy
'Ex: define narr = Character(None)
class ObjectNoneItemStrategy
'Ex: define narr = Character("Mi", what_italic=True)
class ItalicObjectStrategy
class NullStrategy

class ItalicStrategy
class ParenthesisStrategy
'Ex: "{i}What am I thinking! I can't do that... right?{/i}" OR
'Ex: "Player" "{i}What am I thinking! I can't do that... right?{/i}"
class CustomTextTagStrategy
'Ex: "Marco jumps over the fence, scrapping his arm in the process"
class BasicStrategy
class ExpressionCueStrategy
'Ex: mc "*smiles*"
class ExpressionCueAsteriskStrategy
'Ex: mc "~yawns~"
class ExpressionCueTildaStrategy

'File Descriptors
class Reader {
	+readLines(fileURL: Union[str,Path]): FileInfo
  +walkFiles(rootDir:str): List<str>
}
class RenpyReader {
  +walkFiles(rootDir:str,invalid_folders: Union[Set<str>,None], invalid_files:Union[Set<str>,None]): List<str>
}
class Writer {
	+writeLines(fileInfo:FileInfo)
  +backupDir(filePaths:List<str>,backupDirPath:Path)
}
class Deleter {
	+delete(fileURL: str)
}

'ThreadExecutors
class  FileExecutor <<Singleton>>{
	{static}+fileLines(reader:RenpyReader,arg:Namespace): List<FileInfo>
  {static}+writeFiles(writer:Writer,fileInfos:List<FileInfo>)
  {static}+fix_errors(error_txt:Path,reader:Reader)
  {static}-fixFunc(errors: List<RenpyError>)
}

'Narrator
class  NarratorHandler <<Singleton>>{
  {static}+PAUSE_STATEMENTS:tuple<str>
  {static}+DOUBLE_QUOTE: str
  {static}+SINGLE_QUOTE: str
	+remove(fileInfos:List<FileInfo>,args:Namespace): List<Dictionary<str,List<str>>>
  +getIdentNum(line:str):int
  -isComment(line:str):bool
  -isImageLabel(line:str):bool
  -resetLineStats()
  -lineStats(): Tuple<int,int>
	-correctIndent(fileInfos:List<FileInfo>): List<FileInfo>
  -pauseFilter(fileInfos:List<FileInfo>): List<FileInfo>
}
class  ErrorFixer <<Singleton>>{
	-destPat: Regex
	-typePat: Regex
	-lineNumPat: Regex
  -projectDir:Union[str,None]
  +fix(errors: List<RenpyError>,reader:Reader,writer:Writer,deleter:Deleter)
  {static}-addError(errors: Dictionary<str,List<RenpyError>>,error: RenpyError)
  {static}-getError(line:str): RenpyError
  -dedentLines(lines:List<str>,startIndex: int,startIndent: Union[int,None]): List<str>
  -reverseDedentLines(lines:List<str>,startIndex: int): List<str>
	-getErrors(errors_txt:Path, reader:Reader): Dictionary<str,List<RenpyError>>
}
dataclass FileInfo {
  +url:str
  +lines: List<str>
}
dataclass RenpyError {
  +line_num:Union[int,None]
  +file_loc:Union[str,None]
  +category:Union[str,None]
}

'Argument Classes
class CLIParser {
    -parser: ArgumentParser
    -setup()
    -initParser()
    -configureOpts()
    +getArgs(commands:str)
}
class ArgChecker {
    {static}+checkArgs(args: Namespace)
    {static}-validateFolderOrFileArg(folderOrFileArg: Path)
}
class ArgAssembler {
  {static}-validators: Dictionary<str,Type>
  {static}+assemble(args:Namespace)
  {static}-convertFilters(args:Namespace)
  {static}-escape(args:Namespace, arg_filter_val: Union<List<str>,None>>): Union<str,List<str>,None>
  {static}-nargFilter(validator:Union<IValidatorChain,None>,arg_filter: Union<str,List<str>,None>,filterName:str): IValidatorChain
}

enum FilterTag {
  BASIC_CHAR
  ITALIC_NARR
  PARENTHESIS_NARR
  BASIC_NARR
  BASIC_CHAR_OBJ
  NONE_CHAR_OBJ
  EXPRESSION_CUES
  NO_CUSTOM_CHAR_OBJS
  NO_CUSTOM_TEXT_TAGS
  NO_CUSTOM_CHARS
}

'Validator Relations
IValidatorChain <|-- IValidatorChainSolo
IValidatorChainSolo <|-- BasicStrategy
IValidatorChainSolo <|-- CustomTextTagStrategy
IValidatorChainSolo <|-- ParenthesisStrategy
IValidatorChainSolo <|-- ItalicStrategy
IValidatorChain <|-- ObjectStrategy
IValidatorChainSolo <|-- CharacterStrategy
IValidatorChainSolo <|-- ExpressionCueStrategy
IValidatorChainSolo <|-- NullStrategy
ExpressionCueStrategy <|-- ExpressionCueAsteriskStrategy
ExpressionCueStrategy <|-- ExpressionCueTildaStrategy
CharacterStrategy <|-- BasicCharacterStrategy
ObjectStrategy <|-- BasicObjectStrategy
ObjectStrategy <|-- ObjectNoneItemStrategy
ObjectStrategy <|-- ItalicObjectStrategy
Reader <|-- RenpyReader

'Argument Relations
ArgChecker ..> CLIParser : uses
ArgAssembler ..> CLIParser : uses
@enduml
